### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by oxk4r** [hoffimar/android-memorytrainer#1]
Could it be possible to add the option for choose a specific range of numbers for each practice, or use the statistics for practice the most failed (worst learned) ones? 
Thanks a lot for this marvelous app and for your time. Regards.

**Comment by hoffimar** [comment]
Thanks for the feedback, at least the specific range feature should be possible. I'll check and try to implement this feature.

**Comment by hoffimar** [comment]
I added a settings dialog where you can change the lower and upper boundaries for the individual generated numbers, it's on the market.
